language: php

sudo: required
dist: trusty

addons:
  firefox: "47.0.1"
  postgresql: "9.4"
  apt:
    packages:
      - oracle-java9-installer
      - oracle-java9-set-default

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 5.6
 - 7.0
 - 7.1

matrix:
  #allow_failures:
  #- env: DB=pgsql MOODLE_BRANCH=master
  #- env: DB=mysqli MOODLE_BRANCH=master
  exclude:
  - php: 5.6
    env: DB=pgsql MOODLE_BRANCH=master
  - php: 5.6
    env: DB=mysqli MOODLE_BRANCH=master
  - php: 5.6
    env: DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
  - php: 5.6
    env: DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
  - php: 5.6
    env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
  - php: 5.6
    env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
  #- php: 5.6
  #  env: DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
  #- php: 5.6
  #  env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
  fast_finish: true

env:
  global:
    - IGNORE_PATHS=thirdparty
    - BEHAT=yes
  matrix:
    - DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
    #- DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
    - DB=pgsql MOODLE_BRANCH=master
    - DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    #- DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    - DB=mysqli MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

jobs:
  include:
    # Prechecks against latest Moodle stable only.
    - stage: static
      php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
      install:
      - moodle-plugin-ci install --no-init
      script:
      - moodle-plugin-ci phplint
      - moodle-plugin-ci phpcpd
      - moodle-plugin-ci phpmd
      - moodle-plugin-ci codechecker
      - moodle-plugin-ci validate
      - moodle-plugin-ci savepoints
      - moodle-plugin-ci mustache
      - moodle-plugin-ci grunt
    # Smaller build matrix for development builds
    - stage: develop
      php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
      install:
      - moodle-plugin-ci install
      script:
      - moodle-plugin-ci phpunit --coverage-clover
      - moodle-plugin-ci behat

# Default 'test' stage: Unit tests and behat tests against full matrix.

install:
  - moodle-plugin-ci install
script:
  - moodle-plugin-ci phpunit --coverage-clover
  - moodle-plugin-ci behat

after_success:
  - bash <(curl -s https://codecov.io/bash)

stages:
  - static
  - name: develop
    if: branch != master AND (type != pull_request OR head_branch != master) AND (tag IS blank)
  - name: test
    if: branch = master OR (type = pull_request AND head_branch = master) OR (tag IS present)